language: ruby
rvm:
  - 2.2.3

before_script:
  - rake db:create
  - rake db:migrate
  - rake db:test:prepare

script: bundle exec rspec spec

services:
  - mysql

addons:
  code_climate:
    repo_token: 1e6d97ae0607936d00fca52c3c47a5044372dd02f68912947f23db35c36eecda
